version: '3.8'
services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: chess_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    environment:
      - DJANGO_SETTINGS_MODULE=chessWebApp.settings
    depends_on:
      - postgres_db
      - redis
    command: daphne -b 0.0.0.0 -p 8000 --ping-interval 30 --ping-timeout 15 backend.asgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --poll=2000
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8001:80"
    depends_on:
      - postgres_db
    
volumes:
  postgres_data:
